version: '3.7'

services:
  web:
    build:
      context: ./web/
      dockerfile: Dockerfile
    command: gunicorn main:app -b 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/site/web/static
      - media_volume:/home/app/site/media
    expose:
      - 8000
    depends_on:
      - redis
    networks:
      - private

  redis:
    image: redis
    volumes:
      - redis_data:/var/lib/redis/data/
    networks:
      - private

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/site/web/static
      - media_volume:/home/app/site/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.groot.entrypoints=http"
      - "traefik.http.routers.groot.rule=Host(`groot.ninja`)"
      - "traefik.http.middlewares.groot-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.groot.middlewares=groot-https-redirect"
      - "traefik.http.routers.groot-secure.entrypoints=https"
      - "traefik.http.routers.groot-secure.rule=Host(`groot.ninja`)"
      - "traefik.http.routers.groot-secure.tls=true"
      - "traefik.http.routers.groot-secure.tls.certresolver=http"
      - "traefik.http.routers.groot-secure.service=nginx-groot@docker"
      - "traefik.docker.network=traefik-proxy"
    depends_on:
      - web
    networks:
      - private
      - public
      - traefik-proxy

networks:
  private:
    driver: overlay
  public:
    external: true
  traefik-proxy:
    external: true

volumes:
  redis_data:
  static_volume:
  media_volume:
